#!/bin/bash

set -eu

#silver --clean --warn-all -I grammars -I ../Oberon0 --one-jar oberon0:lsp
silver -I grammars -I ../Oberon0 --one-jar oberon0:lsp
hook-into-genericLanguageServer oberon0.lsp.jar

